sudo: required
dist: trusty

env:
  - 

go_import_path: github.com/victoryang/elibot-apiserver

install:
  - chmod +x travis-ci/install.sh && sh -C travis-ci/install.sh

script:
  - cd thirdparty/mcsql/ && make
  - cd ../..

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: elibot-apiserver
  skip_cleanup: true
  on:
    tags: true
