sudo: required
dist: trusty

language: go
go:
  - "1.8"

env:
  - 

go_import_path: github.com/victoryang/elibot-apiserver

install: true
  #- cp travis-ci/libsqlitedb.so /usr/lib/

script:
  - mkdir -p $HOME/gopath/src/elibot-apiserver
  - cp -r $HOME/gopath/src/github.com/victoryang/elibot-apiserver/ $HOME/gopath/src/