sudo: required
dist: trusty

language: go

go:
  - "1.10.x"

install:
  - chmod +x travis-ci/install.sh && sh -C travis-ci/install.sh

script:
  - chmod +x travis-ci/build.sh && sh -C travis-ci/build.sh

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: elibot-apiserver
  skip_cleanup: true
  on:
    tags: true
