sudo: required
dist: trusty

language: go
go:
  - "1.8"

env:
  - 

go_import_path: github.com/victoryang/elibot-apiserver

install:
  - sudo cp travis-ci/libsqlitedb.so /usr/lib/

script:
  - mkdir -p $HOME/gopath/src/elibot-apiserver
  - cp -r $HOME/gopath/src/github.com/victoryang/elibot-apiserver/ $HOME/gopath/src/
  - cd $HOME/gopath/src/elibot-apiserver/
  - chmod +x build/go-build.sh && sh -C build/go-build.sh

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: elibot-apiserver
  skip_cleanup: true
  on:
    tags: true
