sudo: required
dist: trusty

language: go

go:
  - "1.10.x"
go_import_path: ${GOPATH}/src/

go_import_path: github.com/victoryang/elibot-apiserver

install:
  - chmod +x travis-ci/install.sh && sh -C travis-ci/install.sh

script:
  - cp build/lib/libsqlitedb.so /usr/lib/gcc-cross/arm-linux-gnueabihf/4.8
  - cp build/lib/libz.so.1.2.8  /usr/arm-linux-gnueabihf/lib/
  - ln -s /usr/arm-linux-gnueabihf/lib/libz.so.1.2.8 /usr/arm-linux-gnueabihf/lib/libz.so.1
  - mkdir /root/mcserver/
  - tar -xvf build/include/include.tar.gz -C /root/mcserver/
  - cp build/lib/libshare.a /usr/arm-linux-gnueabihf/lib/
  - cd thirdparty/mcsql/ && make
  - cd ../mrj/ && make
  - cd ../..
  - chmod +x travis-ci/build.sh && sh -C travis-ci/build.sh

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: elibot-apiserver
  skip_cleanup: true
  on:
    tags: true
