GO = go
MAKE = make

.PHONY: all

all: api-server

api-server:
	GO111MODULE=on CC=arm-linux-gnueabihf-gcc GOOS=linux GOARCH=arm GOARM=6 CGO_ENABLED=1 $(GO) build -mod=vendor -ldflags "-s -w" -v -o $@

clean:
	rm api-server
